version: '1'

services:
  mysql-server:
    image: mysql:8.0
    # container_name: mi_mysql_server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./datos_mysql:/var/lib/mysql
