export const AdminMenu = {
  mainMenu: [
    {
      id: 1,
      label: 'Dashboard',
      link: '/admin/dashboard',
      icon: 'dashboard',
      tagSubMenu: false,
      permissions: ['admin'],
      subMenu: [],
    },
    {
      id: 2,
      label: 'Matricula',
      link: '/admin/school',
      icon: 'school',
      tagSubMenu: true,
      permissions: ['admin'],
      subMenu: [
        {
          id: 1,
          label: 'Est. por seccion',
          icon: 'table',
          link: '/admin/school/matricula',
          permissions: ['admin'],
        },
        {
          id: 2,
          label: 'Parentesco',
          icon: 'family',
          link: '/admin/school/family',
          permissions: ['admin'],
        },
        {
          id: 3,
          label: 'Familias',
          icon: 'family',
          link: '/admin/school/families',
          permissions: ['admin'],
        },
        {
          id: 4,
          label: 'Vacantes',
          icon: 'family',
          link: '/admin/school/vacants',
          permissions: ['admin'],
        },
      ],
    },
    {
      id: 3,
      label: 'Asistencia',
      link: '/admin/Prueba',
      icon: 'student',
      tagSubMenu: true,
      permissions: [
        'admin',
        'card-generator',
        'attendance-recorder',
        'holiday',
        'schedule',
      ],
      subMenu: [
        {
          id: 1,
          label: 'Día festivo',
          icon: 'calendar',
          link: '/admin/student/holiday',
          permissions: ['admin', 'holiday'],
        },
        {
          id: 2,
          label: 'Estudiantes',
          icon: 'student',
          link: '/admin/student/students',
          permissions: ['admin', 'card-generator'],
        },
        {
          id: 3,
          label: 'Hr. Personalizado',
          icon: 'student',
          link: '/admin/student/daysadditional',
          permissions: ['admin', 'schedule'],
        },
        {
          id: 4,
          label: 'Control Asistencia',
          icon: 'student',
          link: '/admin/student/attendance',
          permissions: ['admin', 'attendance-recorder'],
        },
      ],
    },
    {
      id: 3,
      label: 'Reportes',
      link: '/admin/reports',
      icon: 'report',
      tagSubMenu: true,
      permissions: ['admin', 'report', 'report-student'],
      subMenu: [
        {
          id: 1,
          label: 'Reportes Estudiantes',
          icon: 'tableStudents',
          link: '/admin/reports/students',
          permissions: ['admin', 'report', 'report-student'],
        },
        {
          id: 2,
          label: 'Reporte Global',
          icon: 'reports',
          link: '/admin/reports/report',
          permissions: ['admin'],
        },
        {
          id: 3,
          label: 'Reporte por sede',
          icon: 'reports',
          link: '/admin/reports/report-campus',
          permissions: ['admin', 'report'],
        },
      ],
    },
    {
      id: 4,
      label: 'Usuarios',
      link: '/admin/users',
      icon: 'users',
      tagSubMenu: true,
      permissions: ['admin'],
      subMenu: [
        {
          id: 1,
          label: 'Usuarios',
          icon: 'userAdd',
          link: '/admin/staff/users',
          permissions: ['admin'],
        },
        {
          id: 2,
          label: 'Roles',
          icon: 'userAdd',
          link: '/admin/staff/roles',
          permissions: ['admin'],
        },
      ],
    },
    {
      id: 5,
      label: 'Comunicaciones',
      link: '/admin/emails',
      icon: 'comunication',
      tagSubMenu: true,
      permissions: ['admin'],
      subMenu: [
        {
          id: 1,
          label: 'Correos',
          icon: 'email',
          link: '/admin/emails',
          permissions: ['admin'],
        },
      ],
    },
  ],
  settingsMenu: [
    {
      id: 1,
      label: 'Configuración',
      link: '/admin/dashboard',
      icon: 'setting',
      tagSubMenu: true,
      permissions: ['admin'],
      subMenu: [
        {
          id: 1,
          label: 'Años',
          icon: 'module',
          link: '/admin/configuration/years',
          permissions: ['admin'],
        },
        {
          id: 2,
          label: 'Fases',
          icon: 'module',
          link: '/admin/configuration/phase',
          permissions: ['admin'],
        },
        {
          id: 3,
          label: 'Campus',
          icon: 'module',
          link: '/admin/configuration/campus',
          permissions: ['admin'],
        },
        {
          id: 4,
          label: 'Niveles',
          icon: 'module',
          link: '/admin/configuration/level',
          permissions: ['admin'],
        },
        {
          id: 5,
          label: 'Grados',
          icon: 'module',
          link: '/admin/configuration/grade',
          permissions: ['admin'],
        },
        {
          id: 6,
          label: 'Relacion',
          icon: 'module',
          link: '/admin/configuration/campus-relation',
          permissions: ['admin'],
        },
        {
          id: 7,
          label: 'Turnos',
          icon: 'module',
          link: '/admin/configuration/school-shifts',
          permissions: ['admin'],
        },
        {
          id: 8,
          label: 'Salones',
          icon: 'module',
          link: '/admin/school/classroom',
          permissions: ['admin'],
        },
        {
          id: 9,
          label: 'Aulas',
          icon: 'module',
          link: '/admin/configuration/activity-classroom',
          permissions: ['admin'],
        },
        {
          id: 10,
          label: 'Dias Laborables',
          icon: 'module',
          link: '/admin/student/dayofweek',
          permissions: ['admin'],
        },
        {
          id: 10,
          label: 'Cronograma',
          icon: 'module',
          link: '/admin/enrollment/schedule',
          permissions: ['admin'],
        },
      ],
    },
  ],
};
